language: "en"
pipeline:
#- name: "LanguageModelIntentClassifier"    # This uses a pretrained language model for intent classification
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    entity_recognition: True
  - name: LexicalSyntacticFeaturizer
  - name: CRFEntityExtractor
  - name: DucklingEntityExtractor
    timezone: "Asia/Taipei"


#- name: "EntityExtractor"    # Handles entity extraction
#- name: "RegexEntityExtractor"    # You can use this for extracting entities based on regex patterns

policies:
- name: "RulePolicy"
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
  restrict_rules: false
- name: "MemoizationPolicy"
  max_history: 1
- name: TEDPolicy
  max_history: 5
  epochs: 100
#- name: "FormPolicy"
assistant_id: 20241114-162419-blue-retreat
